name: easypark_flutter
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.3 
  provider: ^6.1.2
  google_maps_flutter: ^2.10.0
  google_maps_flutter_web: ^0.5.10
  geolocator: ^13.0.2
  js: ^0.6.5
  animate_do: ^3.0.2

  url_launcher: ^6.1.14
  http: ^1.3.0
  geocoding: ^2.1.0
  google_fonts: ^6.1.0
  location: ^5.0.3
  google_sign_in: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/custom_marker.png
    - assets/images/easypark_logo_transparent.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/custom_marker.png"

flutter_native_splash:
  color: "#0f2027"
  image: assets/images/easypark_logo_transparent.png
  android: true
  ios: true
  fullscreen: true

